import "./globals.css";
export default function RootLayout({ children }) {
  return (
    <html lang="en" className="w-80 h-80">
      <body className="w-80 h-80 bg-green-400" >
        <main>{children}</main>
      </body>
    </html>
  );
}

// import localFont from "next/font/local";
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
